substitutions:
  _REGION: 'europe-west1'
  _SERVICE_NAME: 'noita-backend'
  _REPO: 'europe-west1-docker.pkg.dev/noita-website/noita-website'
  _CLOUDSQL_INSTANCE: 'noita-website:europe-west1:noita-website-instance'

availableSecrets:
  secretManager:
  - versionName: projects/982182162415/secrets/DB_PASS/versions/latest
    env: 'DB_PASS'
  - versionName: projects/982182162415/secrets/DB_USER/versions/latest
    env: 'DB_USER'
  - versionName: projects/982182162415/secrets/DB_NAME/versions/latest
    env: 'DB_NAME'

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', '${_REPO}/${_SERVICE_NAME}:$SHORT_SHA',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REPO}/${_SERVICE_NAME}:$SHORT_SHA'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', '${_SERVICE_NAME}',
        '--container=cloud-sql-proxy',
        '--image=gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.16.0',
        '--args=--private-ip,--address=0.0.0.0,--port=5432,--structured-logs,${_CLOUDSQL_INSTANCE}',
        '--cpu=0.08',
        '--memory=128Mi',
        '--container=app'
        '--image=${_REPO}/${_SERVICE_NAME}:$SHORT_SHA',
        '--port=8080',
        '--set-env-vars=DB_USER=$$DB_USER,DB_PASS=$$DB_PASS,DB_SSL=false,DB_HOST=127.0.0.1,SERVER_PORT=8080',
        '--set-secrets=DB_PASS=DB_PASS:latest',
        '--depends-on=cloud-sql-proxy',
        '--cpu=0.1',
        '--memory=512Mi',
        '--region=${_REGION}',
        '--platform=managed',
        '--service-account=noita-backend@noita-website.iam.gserviceaccount.com',
        '--no-allow-unauthenticated',
        '--execution-environment=gen2',
        '--cpu-boost',
        '--max-instances=1',
      ]
    secretEnv: ['DB_PASS', 'DB_USER', 'DB_NAME']


images:
  - '${_REPO}/${_SERVICE_NAME}:$SHORT_SHA'

timeout: 900s